aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5t9mpendCkALZKtBcqW1
  accessKeySecret: XXX（你的accessKeySecret）
  bucketName: malf-bucket
  urlPrefix: https://malf-bucket.oss-cn-beijing.aliyuncs.com/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB